[window]
padding = { x = 0, y = 0 }
opacity = 0.8

[scrolling]
multiplier = 1

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
size = 11

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Block", blinking = "Always" }
